# Кузьмичев Никита
## **Домашнее задание №1**

### Тема: настройка рабочей среды, работа с Git, структура репозитория и базовые операции в NumPy.

##### **1. Импорт библиотеки NumPy с общепринятым сокращением.**

In [1]:
import numpy as np

##### **2. Примеры создания массивов:**
#####   - из обычных списков;
#####   - с использованием функций `zeros`, `ones`, `arange` или аналогичных.

In [2]:
a = np.array([1, 2, 3, 4])  # 1D массив из списка целых чисел
b = np.array([[1.0, 2.0], [3.0, 4.0]])  # 2D массив (матрица) из вложенных списков
Zeros = np.zeros((2, 3))  # матрица 2x3, заполненная нулями
Ones = np.ones(5)  # 1D массив из пяти единиц
ar = np.arange(0, 10, 2)  # последовательность 0,2,4,6,8 в виде 1D массива

In [3]:
# Вывод созданных массивов
print("a:", a)
print("b:\n", b)
print("zeros:\n", Zeros)
print("ones:", Ones)
print("ar:", ar)

a: [1 2 3 4]
b:
 [[1. 2.]
 [3. 4.]]
zeros:
 [[0. 0. 0.]
 [0. 0. 0.]]
ones: [1. 1. 1. 1. 1.]
ar: [0 2 4 6 8]


##### **3. Демонстрация атрибутов:**
#####   - вывод формы (shape) и типа данных (dtype) для одного из массивов.

In [4]:
print("--- Атрибуты массива b ---")
print("shape (форма) b:", b.shape) # форма (размерности) массива
print("dtype (тип данных) b:", b.dtype) # тип элементов в массиве

--- Атрибуты массива b ---
shape (форма) b: (2, 2)
dtype (тип данных) b: float64


##### **4. Примеры индексирования и срезов:**
#####   - получение отдельного элемента;
#####   - извлечение подмассива с помощью среза.

In [5]:
# Отдельные элементы
third_element = a[2]  # индексация идёт с нуля, следовательно третий элемент массива a имеет индекс "2"
print("Третий элемент a (a[2]):", third_element)
b_0_1 = b[0, 1]  # элемент первой строки, второго столбца в матрице b
print("Элемент b[0,1]:", b_0_1)

# Подмассивы, полученные срезом
slice_ar = ar[1:4]  # элементы с индексами 1,2,3 (4 индекс не берётся)
print("\nСрез ar[1:4]:", slice_ar)
col0 = b[:, 0]  # все строки первого столбца
print("Первый столбец b:", col0)

Третий элемент a (a[2]): 3
Элемент b[0,1]: 2.0

Срез ar[1:4]: [2 4 6]
Первый столбец b: [1. 3.]


##### **5. Примеры векторных операций и базовых статистик:**
#####   - поэлементное сложение или умножение массивов;
#####   - вычисление средней величины (`mean`) или другой простой статистики.

In [6]:
c = np.array([10, 20, 30, 40])
d = np.array([1, 2, 3, 4])

In [7]:
sum_cd = c + d
prod_cd = c * d
print("Поэлементное сложение c+d:", sum_cd)
print("Поэлементное умножение c*d:", prod_cd)

Поэлементное сложение c+d: [11 22 33 44]
Поэлементное умножение c*d: [ 10  40  90 160]


In [8]:
mean_c = c.mean() # среднее значение элементов массива c
mean_d = np.mean(d) # среднее по всем элементам массива d (эта функция то же самое, что и *переменная*.mean(), только более универсальная)
max_c = c.max()
min_c = c.min()
print("mean(c):", mean_c)
print("mean(b):", mean_b)
print("max(c):", max_c)
print("min(c):", min_c)

mean(c): 25.0


NameError: name 'mean_b' is not defined